customer_insights:
 my_project:
  target: prod
  outputs:
    prod:
      dbname: postgres
      host: 34.162.96.20
      pass: deebeetee
      port: 5432
      schema: airflowDbtSchema
      threads: 1
      type: postgres
      user: postgres